name: Auction House Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn package

      - name: Transfer main branch to Tweetzy
        id: push_directory
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        uses: cpina/github-action-push-to-another-repository@master
        with:
          source-directory: '.'
          destination-github-username: 'Tweetzy'
          destination-repository-name: 'Auction-House'
          user-email: 'kiran.hart@live.com'
          commit-message: See ORIGIN_COMMIT
