name: Auction House Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn package

      - name: Transfer main branch to Tweetzy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: /.
          dst_owner: Tweetzy
          dst_repo_name: Auction-House
          email: kiran.hart@live.com
          src_branch: main
          dst_branch: master

